import os

from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)

styles = getSampleStyleSheet()


def add_header_footer(canvas, doc):

    width, height = doc.pagesize

    # Header Line
    canvas.line(40, height - 80, width - 40, height - 80)

    # Footer Line
    canvas.line(40, 50, width - 40, 50)

    # Footer Text
    canvas.setFont("Helvetica", 9)

    canvas.drawString(
        40,
        35,
        "Generated by ABC Analytics Pvt Ltd"
    )

    canvas.drawRightString(
        width - 40,
        35,
        f"Page {doc.page}"
    )


def create_pdf(

    output_path,
    report_text,
    chart_path

):

    doc = SimpleDocTemplate(output_path)

    story = []

    logo_path = "assets/logo.png"

    if os.path.exists(logo_path):

        logo = Image(
            logo_path,
            width=0.8 * inch,
            height=0.8 * inch
        )

        story.append(logo)

    title = styles["Heading1"]

    title.alignment = TA_CENTER

    story.append(

        Paragraph(

            "ABC Analytics Pvt Ltd",

            title

        )

    )

    story.append(

        Paragraph(

            "<b>Data Driven Decisions with AI</b>",

            styles["BodyText"]

        )

    )

    story.append(

        Spacer(

            1,

            0.3 * inch

        )

    )

    story.append(

        Paragraph(

            "<b>AI Generated Data Analysis Report</b>",

            styles["Heading2"]

        )

    )

    story.append(

        Spacer(

            1,

            0.3 * inch

        )

    )

    # Visualization

    if os.path.exists(chart_path):

        chart = Image(

            chart_path,

            width=6 * inch,

            height=3.5 * inch

        )

        story.append(chart)

        story.append(

            Spacer(

                1,

                0.3 * inch

            )

        )

    story.append(

        Paragraph(

            "<b>Executive Summary</b>",

            styles["Heading2"]

        )

    )

    story.append(

        Paragraph(

            report_text,

            styles["BodyText"]

        )

    )

    doc.build(

        story,

        onFirstPage=add_header_footer,

        onLaterPages=add_header_footer

    )